### ISSUE TITLE
Is there a way to speed up the compile step?

### ISSUE THREAD

**Issue by dagumak** [hawku-com/ex_web3_ec_recover#11]
This is probably more so a rust issue than anything, but it seems like the `ex_secp256k1` dependency takes a significant time to compile. Is there a way to make it faster?

**Comment by grahac** [comment]
Yeah. It takes a while for us too and likely is Rust-related. Given ex_secp256k1 is a separate library,  I believe this may be a good question for the ex_secp256k1 github? (https://github.com/omgnetwork/ex_secp256k1)

**Comment by dagumak** [comment]
Posted here: https://github.com/omgnetwork/ex_secp256k1/issues/13
