### ISSUE TITLE
Error when including this lib as a dependency on mix.exs

### ISSUE THREAD

**Issue by spapas** [hawku-com/ex_web3_ec_recover#6]
Hello, when I add the line `{:ex_web3_ec_recover, "~> 0.1.0"},` in my mix.exs I get the following error when running `iex -S mix`:

```
* ex_web3_ec_recover (Hex package)
  could not find an app file at "_build/dev/lib/ex_web3_ec_recover/ebin/ex_web3_ec_recover.app". Another app file was found in the same directory "_build/dev/lib/ex_web3_ec_recover/ebin/ex_web3_recover_signature.app", try changing the dependency name to :ex_web3_recover_signature
```

I was able to surpress this error by changing the line to `{:ex_web3_ec_recover, "~> 0.1.0", app: false},`. After that the `ExWeb3EcRecover.recover_personal_signature` function worked flawlessly.

 Could you change the library to use the correct app name or update the docs to reflect the correct dependency ?

Thank you!

**Comment by grahac** [comment]
@spapas Thank you for finding and reporting this!
